services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: romus
      POSTGRES_PASSWORD: romus
      POSTGRES_DB: romus
    ports:
      - "5432:5432"
    volumes:
      - romus_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  romus_pgdata:
