"""add sets and reps tables

Revision ID: f57f74872966
Revises: 71a8f9a0111d
Create Date: 2026-04-25 15:25:43.425978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f57f74872966'
down_revision: Union[str, Sequence[str], None] = '71a8f9a0111d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('set_index', sa.Integer(), nullable=False),
    sa.Column('weight_lb', sa.Float(), nullable=False),
    sa.Column('rep_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sets_session_id'), 'sets', ['session_id'], unique=False)
    op.create_table('reps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('rep_index', sa.Integer(), nullable=False),
    sa.Column('depth_cm', sa.Float(), nullable=True),
    sa.Column('time_to_lift_ms', sa.Integer(), nullable=True),
    sa.Column('low_confidence', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reps_set_id'), 'reps', ['set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reps_set_id'), table_name='reps')
    op.drop_table('reps')
    op.drop_index(op.f('ix_sets_session_id'), table_name='sets')
    op.drop_table('sets')
    # ### end Alembic commands ###
